import { useEffect, useState } from "react";

import { api } from "../api/client";
import { MarkdownView } from "../components/MarkdownView";
import { useProjectContext } from "../components/ProjectContext";

const CANDIDATES = [
  "_aggregator/estimation/Estimation-ModuleOverallHrs.md",
  "_aggregator/estimation/Estimation-ModuleBuildHrs.md",
  "_aggregator/estimation/Estimation-BusinessReqDetail.md",
];

export function EstimationView() {
  const { project } = useProjectContext();
  const [selected, setSelected] = useState<string>(CANDIDATES[0]);
  const [body, setBody] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!project) {
      setBody(null);
      return;
    }
    setLoading(true);
    setError(null);
    const fullPath = `projects/${project}/${selected}`;
    api.docContent(fullPath)
      .then(r => setBody(r.content))
      .catch(e => {
        setError(String(e));
        setBody(null);
      })
      .finally(() => setLoading(false));
  }, [project, selected]);

  if (!project) {
    return (
      <section className="page">
        <h2>Estimation view</h2>
        <p className="empty">Pick a project first.</p>
      </section>
    );
  }

  return (
    <section className="page">
      <h2>Estimation view -- {project}</h2>
      <p className="page-desc">Solution-estimate aggregator outputs. Generated by <code>/solution-estimate:estimate</code>.</p>
      <div className="row">
        <label>Deliverable:</label>
        <select value={selected} onChange={e => setSelected(e.target.value)}>
          {CANDIDATES.map(c => <option key={c} value={c}>{c.split("/").pop()}</option>)}
        </select>
      </div>
      {loading && <div className="loading">Loading...</div>}
      {error && <div className="error">{error} -- run <code>/solution-estimate:estimate</code> to generate it.</div>}
      {body && <MarkdownView source={body} />}
    </section>
  );
}
