/**
 * Doc-lint validators — deterministic rules enforced on every generated doc.
 * Rules per design/07-doc-rules.md + design/11-mcp-server.md § doc-lint.
 *
 * Each validator returns Finding[]; an empty array means "no issues".
 */

import { extractFrontmatter } from "../../lib/file-utils.js";

export type Severity = "BLOCKER" | "REQUIRED" | "WARNING";

export type Finding = {
  rule: string;
  severity: Severity;
  line?: number;          // 1-based line number when locatable
  message: string;
};

/**
 * Required frontmatter keys for every generated doc.
 * Some doc kinds (e.g., ADRs, design docs) have a different required-key set.
 * Callers can pass `requiredKeys` to override the default per doc kind.
 */
const DEFAULT_REQUIRED_FRONTMATTER_KEYS = [
  "feature-id",
  "agent",
  "phase",
  "schema-version",
];

export type LintOptions = {
  /** Optional override for the required frontmatter keys (e.g., for ADRs/design docs). */
  requiredFrontmatterKeys?: string[];
  /** Optional set of rules to skip (rare; used by --waive-coverage etc.). */
  skipRules?: string[];
};

export function lintDocument(
  content: string,
  opts: LintOptions = {}
): Finding[] {
  const findings: Finding[] = [];
  const skipped = new Set(opts.skipRules ?? []);
  const required = opts.requiredFrontmatterKeys ?? DEFAULT_REQUIRED_FRONTMATTER_KEYS;

  const { frontmatter, body } = extractFrontmatter(content);

  // R1 — Frontmatter present with required keys
  if (!skipped.has("frontmatter-required")) {
    if (frontmatter === null) {
      findings.push({
        rule: "frontmatter-required",
        severity: "BLOCKER",
        line: 1,
        message: "Missing YAML frontmatter block (--- ... ---)",
      });
    } else {
      for (const key of required) {
        if (!(key in frontmatter) || frontmatter[key] === undefined || frontmatter[key] === null || frontmatter[key] === "") {
          findings.push({
            rule: "frontmatter-required",
            severity: "BLOCKER",
            line: 1,
            message: `Frontmatter missing required key: '${key}'`,
          });
        }
      }
    }
  }

  // R2 — Auto-generated TOC at top of multi-section docs
  if (!skipped.has("toc-required")) {
    const sectionCount = (body.match(/^##\s+/gm) ?? []).length;
    if (sectionCount >= 3) {
      const hasToc =
        /<!--\s*TOC\b/i.test(body) ||
        /\bAUTO-GENERATED BY doc_lint\b/i.test(body) ||
        /^##\s+Table of Contents/im.test(body);
      if (!hasToc) {
        findings.push({
          rule: "toc-required",
          severity: "REQUIRED",
          message: `Doc has ${sectionCount} sections (>= 3) but no TOC marker. Insert "<!-- TOC AUTO-GENERATED BY doc_lint -->" near the top.`,
        });
      }
    }
  }

  // R3 — Mermaid only for diagrams (no PNG, no draw.io, no img tags pointing to .png/.jpg/.svg)
  if (!skipped.has("mermaid-only")) {
    const lines = body.split(/\r?\n/);
    lines.forEach((line, idx) => {
      // Markdown image
      const imgMatch = line.match(/!\[[^\]]*\]\(([^)]+)\)/);
      if (imgMatch) {
        const url = imgMatch[1].toLowerCase();
        if (/\.(png|jpe?g|gif|svg|bmp|webp)(?:$|[?#])/.test(url) || url.includes("draw.io")) {
          findings.push({
            rule: "mermaid-only",
            severity: "BLOCKER",
            line: idx + 1,
            message: `Image reference not allowed: '${imgMatch[1]}'. Use a Mermaid code block instead.`,
          });
        }
      }
      // HTML img tag
      if (/<img\s+/i.test(line)) {
        findings.push({
          rule: "mermaid-only",
          severity: "BLOCKER",
          line: idx + 1,
          message: "HTML <img> tag not allowed. Use a Mermaid code block instead.",
        });
      }
    });
  }

  // R4 — Numbered sections (FR-NN / TS-NN / TC-NN style) for cross-reference
  // We only WARN here because not every doc needs numbered sections (e.g., ADRs don't).
  if (!skipped.has("numbered-sections") && frontmatter?.["schema-version"] !== undefined) {
    const sv = String(frontmatter["schema-version"]);
    if (sv.startsWith("spec.") || sv.startsWith("plan.") || sv.startsWith("tdd.")) {
      const hasNumbered = /\b(FR|TS|TC)-\d{2,}\b/.test(body);
      if (!hasNumbered) {
        findings.push({
          rule: "numbered-sections",
          severity: "WARNING",
          message: `Doc kind '${sv}' should contain numbered section IDs (FR-NN / TS-NN / TC-NN). None found.`,
        });
      }
    }
  }

  // R5 — AI Summary section at top
  if (!skipped.has("ai-summary-required")) {
    const hasAiSummary = /^##\s+AI Summary\b/im.test(body);
    if (!hasAiSummary) {
      findings.push({
        rule: "ai-summary-required",
        severity: "BLOCKER",
        message: "Missing '## AI Summary' section at the top of the doc body.",
      });
    }
  }

  // R6 — Traceability matrix at bottom (spec / plan / tdd)
  if (!skipped.has("traceability-matrix") && frontmatter?.["schema-version"] !== undefined) {
    const sv = String(frontmatter["schema-version"]);
    if (sv.startsWith("spec.") || sv.startsWith("plan.") || sv.startsWith("tdd.")) {
      const hasTraceability = /^##\s+(Traceability|.*Traceability matrix)\b/im.test(body);
      if (!hasTraceability) {
        findings.push({
          rule: "traceability-matrix",
          severity: "REQUIRED",
          message: `Doc kind '${sv}' should end with a Traceability matrix section.`,
        });
      }
    }
  }

  // R7 — No inline ALM IDs (only section IDs)
  if (!skipped.has("no-inline-alm-ids")) {
    // ADO style: "AB#123" or "ADO #123". JIRA style: "PROJ-1234" but exclude FR-NN/TS-NN/TC-NN/AC-NN/L1-NN.
    // We look for ADO pattern conservatively to avoid false positives on requirement IDs.
    const lines = body.split(/\r?\n/);
    lines.forEach((line, idx) => {
      if (/\bAB#\d+\b/i.test(line) || /\bADO #\d+\b/i.test(line)) {
        findings.push({
          rule: "no-inline-alm-ids",
          severity: "BLOCKER",
          line: idx + 1,
          message: "Inline ADO work-item ID detected. ALM IDs belong in work-items.yaml; use section IDs (FR-NN/TS-NN) in markdown.",
        });
      }
    });
  }

  // R8 — Quality self-check appendix on FDD / TDD / blueprint / test-plan (per ADR-0001)
  if (!skipped.has("quality-self-check") && frontmatter?.["schema-version"] !== undefined) {
    const sv = String(frontmatter["schema-version"]);
    const requiresAppendix =
      sv.startsWith("fdd.") ||
      sv.startsWith("tdd.") ||
      sv.startsWith("blueprint.") ||
      sv.startsWith("test-plan.");
    if (requiresAppendix) {
      const hasAppendix = /^##\s+Quality self-check\b/im.test(body);
      if (!hasAppendix) {
        findings.push({
          rule: "quality-self-check",
          severity: "BLOCKER",
          message: `Doc kind '${sv}' must include a '## Quality self-check' appendix populated by the inline self-check (ADR-0001).`,
        });
      }
    }
  }

  // R9 — feature-id HTML-comment markers on domain-doc section blocks
  // We can only meaningfully enforce this when frontmatter declares this is a domain doc.
  // Domain-scoped FDD/TDD/blueprint per ADR-0006 carry a `doc-scope: domain` frontmatter key.
  if (!skipped.has("feature-id-markers") && frontmatter?.["doc-scope"] === "domain") {
    // Each ## block should be preceded by `<!-- feature-id: ... -->` on the line above OR on the same line set.
    const lines = body.split(/\r?\n/);
    lines.forEach((line, idx) => {
      if (/^##\s+/.test(line)) {
        // Look 1-2 lines above for the marker (allowing blank line).
        const prev1 = lines[idx - 1] ?? "";
        const prev2 = lines[idx - 2] ?? "";
        const hasMarker = /<!--\s*feature-id:/.test(prev1) || /<!--\s*feature-id:/.test(prev2);
        if (!hasMarker) {
          findings.push({
            rule: "feature-id-markers",
            severity: "BLOCKER",
            line: idx + 1,
            message: `Domain doc section missing '<!-- feature-id: {slug} -->' marker on the preceding line(s).`,
          });
        }
      }
    });
  }

  return findings;
}

export function summarize(findings: Finding[]): {
  pass: boolean;
  bySeverity: Record<Severity, number>;
  totalCount: number;
  blockerCount: number;
} {
  const bySeverity: Record<Severity, number> = { BLOCKER: 0, REQUIRED: 0, WARNING: 0 };
  for (const f of findings) {
    bySeverity[f.severity]++;
  }
  return {
    pass: bySeverity.BLOCKER === 0,
    bySeverity,
    totalCount: findings.length,
    blockerCount: bySeverity.BLOCKER,
  };
}
