import { readFileSync, readdirSync, writeFileSync, mkdirSync, existsSync } from 'fs'
import { join, dirname, basename } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(__dirname, '..', '..', '..')

const AGENT_DEFS = [
  { id: 'd365-ce',            name: 'D365 Customer Engagement',   description: 'Dynamics 365 CE — Plugins, PCF, JS, Dataverse',        commandsDir: join(repoRoot, 'templates', 'd365-ce', '.claude', 'commands') },
  { id: 'd365-ce-brownfield', name: 'D365 CE Brownfield',         description: 'CE reverse engineering & documentation',               commandsDir: join(repoRoot, 'templates', 'd365-ce-brownfield', '.claude', 'commands') },
  { id: 'd365-fo',            name: 'D365 Finance & Operations',  description: 'Dynamics 365 FO — X++, Data Entities',                commandsDir: join(repoRoot, 'templates', 'd365-fo', '.claude', 'commands') },
  { id: 'integration',        name: 'Azure Integration',          description: 'Azure Functions, Logic Apps, APIM, Bicep',            commandsDir: join(repoRoot, 'templates', 'integration', '.claude', 'commands') },
  { id: 'power-apps',         name: 'Power Apps',                 description: 'Canvas, Model-Driven, Power Automate',               commandsDir: join(repoRoot, 'templates', 'power-apps', '.claude', 'commands') },
  { id: 'data-migration',     name: 'Data Migration',             description: 'Data Migration & ADF Pipelines',                     commandsDir: join(repoRoot, 'templates', 'data-migration', '.claude', 'commands') },
  { id: 'reporting',          name: 'Reporting',                  description: 'Power BI, SSRS, DAX Measures, RLS, Datasets',        commandsDir: join(repoRoot, 'templates', 'reporting', '.claude', 'commands') },
  { id: 'solution-architect', name: 'Solution Architect',         description: 'Cross-domain blueprint synthesis',                   commandsDir: join(repoRoot, 'templates', 'solution-architect', '.claude', 'commands') },
  { id: 'solution-estimate',  name: 'Solution Estimate',          description: 'Factor-based ROM estimation',                        commandsDir: join(repoRoot, 'templates', 'solution-estimate', '.claude', 'commands') },
  { id: 'alm-agent',          name: 'ALM Agent',                  description: 'Azure DevOps work items, tests, wiki, pipelines',    commandsDir: join(repoRoot, 'tools', 'alm-agent', '.claude', 'commands') },
]

function loadCommands(commandsDir) {
  if (!existsSync(commandsDir)) return []
  return readdirSync(commandsDir).filter(f => f.endsWith('.md')).sort().map(file => ({
    id: basename(file, '.md'),
    name: basename(file, '.md'),
    content: readFileSync(join(commandsDir, file), 'utf-8'),
    isReadme: false,
  }))
}

function loadReadme(commandsDir) {
  const p = join(commandsDir, '..', '..', 'README.md')
  return existsSync(p) ? readFileSync(p, 'utf-8') : null
}

const agents = AGENT_DEFS.map(def => {
  const commands = loadCommands(def.commandsDir)
  const readmeContent = loadReadme(def.commandsDir)
  const readme = readmeContent ? [{ id: '__readme__', name: 'README', content: readmeContent, isReadme: true }] : []
  return { id: def.id, name: def.name, description: def.description, commands: [...readme, ...commands] }
})

const outDir = join(__dirname, '..', 'src', 'data')
if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true })

writeFileSync(
  join(outDir, 'agents-data.js'),
  `// Auto-generated by scripts/generate-data.js — do not edit\nexport const agents = ${JSON.stringify(agents, null, 2)};\n`
)

const totalCommands = agents.reduce((sum, a) => sum + a.commands.filter(c => !c.isReadme).length, 0)
console.log(`✅  Generated data: ${agents.length} agents, ${totalCommands} commands`)
agents.forEach(a => console.log(`   ${a.id.padEnd(24)} ${a.commands.filter(c => !c.isReadme).length} commands`))
