<#
.SYNOPSIS
Create a new project skeleton under projects/{Name}/.

.DESCRIPTION
Creates the per-project state layout described in design/05-project-layout.md:
  - projects/{Name}/project.config.yaml      (validated against schemas/project-config.v1.json)
  - projects/{Name}/work-items.yaml          (skeleton; validated against schemas/work-items.v1.json)
  - projects/{Name}/_handoffs/.keep          (folder placeholder)
  - projects/{Name}/{agent}/                 (per-agent subfolder for each agent in -Agents)
  - projects/{Name}/{agent}/features/        (only if agent has any docScope; aggregators get just the root)
  - projects/{Name}/_brownfield/input/       (only if -Mode brownfield)
  - projects/{Name}/_aggregator/             (always, for solution-architect / solution-estimate outputs)

Validates each generated config file against its v1 JSON Schema via the MCP server's
schema-validate library (compiled JS at tools/mcp-server/dist/lib/schema-validate.js).

.PARAMETER Name
Project slug. Lowercase letters, digits, hyphens. Must match the pattern in project-config.v1.json.

.PARAMETER Description
Human-readable description.

.PARAMETER Agents
Comma-separated list of agent names from agents.yaml. Each must exist in the registry.

.PARAMETER Mode
'greenfield' (default) or 'brownfield'. Brownfield creates _brownfield/ and sets brownfieldPath.

.PARAMETER AlmTool
'ado' (default) or 'jira'. Drives the default alm.hierarchy.

.PARAMETER PublisherPrefix
CE solution publisher prefix (default: first 4 chars of Name).

.PARAMETER Force
Overwrite an existing project folder.

.EXAMPLE
.\tools\scaffold\New-Project.ps1 -Name 'acme-d365' -Description 'ACME D365 CE rollout' -Agents 'd365-ce,integration,alm' -Mode greenfield -AlmTool ado
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$Name,
    [string]$Description = "",
    [Parameter(Mandatory=$true)][string]$Agents,
    [ValidateSet('greenfield','brownfield')][string]$Mode = 'greenfield',
    [ValidateSet('ado','jira')][string]$AlmTool = 'ado',
    [string]$PublisherPrefix = $null,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

# Load helpers
. (Join-Path $PSScriptRoot 'lib/Read-AgentsYaml.ps1')

# Validate project name pattern (matches project-config.v1.json)
if ($Name -notmatch '^[a-z0-9][a-z0-9-]*$') {
    throw "Invalid -Name '$Name'. Must match ^[a-z0-9][a-z0-9-]*$ (lowercase letters, digits, hyphens; starts with letter/digit)."
}

$repoRoot = Find-RepoRoot -StartDir $PSScriptRoot
Write-Host "Repo root: $repoRoot"

# Load + validate -Agents against registry
$registry = Read-AgentsYaml -RepoRoot $repoRoot
$registryNames = $registry | ForEach-Object { $_.Name }
$requestedAgents = $Agents -split ',' | ForEach-Object { $_.Trim() }
foreach ($a in $requestedAgents) {
    if ($registryNames -notcontains $a) {
        throw "Agent '$a' is not in agents.yaml. Known agents: $($registryNames -join ', ')"
    }
}

# Project folder
$projectDir = Join-Path $repoRoot "projects/$Name"
if (Test-Path $projectDir) {
    if (-not $Force) {
        throw "Project folder already exists at $projectDir. Use -Force to overwrite."
    }
    Write-Host "Removing existing $projectDir (Force)" -ForegroundColor Yellow
    Remove-Item -Recurse -Force $projectDir
}

New-Item -ItemType Directory -Path $projectDir -Force | Out-Null
Write-Host "Created: $projectDir"

# Default publisher prefix
if ([string]::IsNullOrWhiteSpace($PublisherPrefix)) {
    $PublisherPrefix = ($Name -replace '[^a-z0-9]','').Substring(0, [Math]::Min(4, ($Name -replace '[^a-z0-9]','').Length))
    if (-not $PublisherPrefix) { $PublisherPrefix = 'acme' }
}

# Resolve ALM hierarchy default
$almHierarchy = if ($AlmTool -eq 'jira') {
    @('Initiative','Epic','Story','Sub-task')
} else {
    @('Epic','Feature','User Story','Task')
}

# Build project.config.yaml content (hand-formatted YAML for stability)
$cfgLines = @()
$cfgLines += "# project.config.yaml - generated by New-Project.ps1"
$cfgLines += "# Validated against schemas/project-config.v1.json"
$cfgLines += ""
$cfgLines += "name: $Name"
if ($Description) { $cfgLines += "description: ""$Description""" }
$cfgLines += "mode: $Mode"
if ($Mode -eq 'brownfield') {
    $cfgLines += "brownfieldPath: projects/$Name/_brownfield"
}
$cfgLines += ""
$cfgLines += "agents-enabled:"
foreach ($a in $requestedAgents) {
    $cfgLines += "  - $a"
}
$cfgLines += ""
$cfgLines += "prefixes:"
$cfgLines += "  publisher: $PublisherPrefix"
$cfgLines += "  solutionName: ${PublisherPrefix}Core"
$cfgLines += "  schemaPrefix: $PublisherPrefix"
$cfgLines += ""
$cfgLines += "multilingual:"
$cfgLines += "  crm: false"
$cfgLines += "  portal: false"
$cfgLines += "  canvas: false"
$cfgLines += "  reports: false"
$cfgLines += "  defaultLanguage: en-US"
$cfgLines += "  supportedLanguages:"
$cfgLines += "    - en-US"
$cfgLines += ""
$cfgLines += "unitTestPolicy:"
$cfgLines += "  plugin: required"
$cfgLines += "  js: required"
$cfgLines += "  pcf: required"
$cfgLines += "  canvas: optional"
$cfgLines += "  portal: required"
$cfgLines += "  ssrs: optional"
$cfgLines += "  power-bi: optional"
$cfgLines += ""
$cfgLines += "nfr:"
$cfgLines += "  responseTimeMsP95: 2000"
$cfgLines += "  availability: 99.5"
$cfgLines += "  errorRate: 0.5"
$cfgLines += ""
$cfgLines += "alm:"
$cfgLines += "  tool: $AlmTool"
$cfgLines += "  hierarchy:"
foreach ($lvl in $almHierarchy) { $cfgLines += "    - $lvl" }
$cfgLines += "  syncOnApprove: false"
$cfgLines += "  readOnlyLevels: []"

$cfgPath = Join-Path $projectDir 'project.config.yaml'
$cfgLines -join "`n" | Set-Content -Path $cfgPath -Encoding UTF8
Write-Host "Wrote: $cfgPath"

# Validate project.config.yaml against schema (via Node helper)
$validatorScript = Join-Path $repoRoot 'tools/scaffold/lib/Validate-Config.cjs'
if (Test-Path $validatorScript) {
    $validateResult = & node $validatorScript $cfgPath 'project-config.v1.json' 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Warning "Validation failed for $cfgPath`:`n$validateResult"
    } else {
        Write-Host "Validated $cfgPath against project-config.v1.json" -ForegroundColor Green
    }
} else {
    Write-Verbose "No JS validator found at $validatorScript; skipping schema check"
}

# Skeleton work-items.yaml
$wiLines = @()
$wiLines += "# work-items.yaml - generated by New-Project.ps1. Skeleton only."
$wiLines += "# /alm-extract populates this file's per-feature L1-L4 hierarchy."
$wiLines += ""
$wiLines += "schemaVersion: ""1.0"""
$wiLines += "project: $Name"
$wiLines += "agents:"
foreach ($a in $requestedAgents) {
    $wiLines += "  ${a}:"
    $wiLines += "    features: {}"
}
$wiPath = Join-Path $projectDir 'work-items.yaml'
$wiLines -join "`n" | Set-Content -Path $wiPath -Encoding UTF8
Write-Host "Wrote: $wiPath"

# _handoffs/ folder
$handoffsDir = Join-Path $projectDir '_handoffs'
New-Item -ItemType Directory -Path $handoffsDir -Force | Out-Null
New-Item -ItemType File -Path (Join-Path $handoffsDir '.keep') -Force | Out-Null
Write-Host "Created: $handoffsDir"

# _aggregator/ folder (for solution-architect / solution-estimate / future aggregator outputs)
$aggregatorDir = Join-Path $projectDir '_aggregator'
New-Item -ItemType Directory -Path (Join-Path $aggregatorDir 'architecture') -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $aggregatorDir 'estimation/inputs') -Force | Out-Null
New-Item -ItemType File -Path (Join-Path $aggregatorDir 'architecture/.keep') -Force | Out-Null
New-Item -ItemType File -Path (Join-Path $aggregatorDir 'estimation/inputs/.keep') -Force | Out-Null
Write-Host "Created: $aggregatorDir"

# _brownfield/ folder (only when mode is brownfield)
if ($Mode -eq 'brownfield') {
    $bfDir = Join-Path $projectDir '_brownfield'
    New-Item -ItemType Directory -Path (Join-Path $bfDir 'input') -Force | Out-Null
    New-Item -ItemType Directory -Path (Join-Path $bfDir 'docs-generated') -Force | Out-Null
    New-Item -ItemType File -Path (Join-Path $bfDir 'input/.keep') -Force | Out-Null
    New-Item -ItemType File -Path (Join-Path $bfDir 'docs-generated/.keep') -Force | Out-Null
    Write-Host "Created (brownfield mode): $bfDir"
}

# Per-agent subfolders
foreach ($agentName in $requestedAgents) {
    $agentDir = Join-Path $projectDir $agentName
    New-Item -ItemType Directory -Path $agentDir -Force | Out-Null

    $agentInfo = Get-AgentByName -Agents $registry -Name $agentName

    # Per-agent _handoffs/ for outgoing handoffs (per design/05-project-layout.md)
    New-Item -ItemType Directory -Path (Join-Path $agentDir '_handoffs') -Force | Out-Null
    New-Item -ItemType File -Path (Join-Path $agentDir '_handoffs/.keep') -Force | Out-Null

    # features/ subfolder only if the agent has at least one docScope key OR base commands
    # (aggregators and alm don't have features/)
    $hasFeatures = $agentInfo.BaseCommands -eq $true
    if ($hasFeatures) {
        New-Item -ItemType Directory -Path (Join-Path $agentDir 'features') -Force | Out-Null
        New-Item -ItemType File -Path (Join-Path $agentDir 'features/.keep') -Force | Out-Null
    }
    Write-Host "Created: $agentDir (features dir: $hasFeatures)"
}

Write-Host ""
Write-Host "Project '$Name' scaffolded successfully at $projectDir" -ForegroundColor Green
Write-Host "Next steps:"
Write-Host "  - Add features:  .\tools\scaffold\New-Feature.ps1 -Project $Name -Agent <agent> -Feature <feature-slug>"
Write-Host "  - Review:        Get-ChildItem -Recurse $projectDir"
